name: DevSecOps

on:
  workflow_dispatch

jobs:
  devsecops:
    name: DevSecOps
    uses: dso-workflows/io-workflows/.github/workflows/devsecops.yml@main
    with:
      verbose-option: 'SilentlyContinue'
      project-language: 'Java,JavaScript'
    secrets: inherit
